const compatibility = {
    'rat': {
        'rat': 'Лад',
        'bull': '-3',
        'tiger': '-3',
        'rabbit': '-7',
        'dragon': '-3',
        'snake': '-7',
        'horse': '-4',
        'goat': '-3',
        'monkey': '-4',
        'rooster': '-5',
        'dog': '-3',
        'boar': '-4'
    },
    'bull': {
        'rat': '+3',
        'bull': 'Лад',
        'tiger': '+7',
        'rabbit': '-3',
        'dragon': '-5',
        'snake': '-1',
        'horse': '-6',
        'goat': '+3',
        'monkey': '+3',
        'rooster': '+1',
        'dog': '-7',
        'boar': '-3'
    },
    'tiger': {
        'rat': '+3',
        'bull': '-7',
        'tiger': 'Лад',
        'rabbit': '-3',
        'dragon': '-3',
        'snake': '+5',
        'horse': '+1',
        'goat': '+7',
        'monkey': '-3',
        'rooster': '+7',
        'dog': '-2',
        'boar': '-1'
    },
    'rabbit': {
        'rat': '+7',
        'bull': '-3',
        'tiger': '-3',
        'rabbit': 'Лад',
        'dragon': '+5',
        'snake': '-3',
        'horse': '-3',
        'goat': '-1',
        'monkey': '+3',
        'rooster': '-7',
        'dog': '+2',
        'boar': '+1'
    },
    'dragon': {
        'rat': '+3',
        'bull': '+5',
        'tiger': '+3',
        'rabbit': '+5',
        'dragon': 'Лад',
        'snake': '-3',
        'horse': '+3',
        'goat': '-7',
        'monkey': '-1',
        'rooster': '+3',
        'dog': '+5',
        'boar': '-5'
    },
    'snake': {
        'rat': '+7',
        'bull': '+1',
        'tiger': '-5',
        'rabbit': '-3',
        'dragon': '+3',
        'snake': 'Лад',
        'horse': '+3',
        'goat': '-7',
        'monkey': '+3',
        'rooster': '+2',
        'dog': '+3',
        'boar': '+3'
    },
    'horse': {
        'rat': '-4',
        'bull': '+6',
        'tiger': '-1',
        'rabbit': '-3',
        'dragon': '-3',
        'snake': '-3',
        'horse': 'Лад',
        'goat': '-3',
        'monkey': '-4',
        'rooster': '+3',
        'dog': '-1',
        'boar': '+5'
    },
    'goat': {
        'rat': '+3',
        'bull': '-3',
        'tiger': '-7',
        'rabbit': '-1',
        'dragon': '+7',
        'snake': '+7',
        'horse': '+3',
        'goat': 'Лад',
        'monkey': '+4',
        'rooster': '-3',
        'dog': '-3',
        'boar': '+1'
    },
    'monkey': {
        'rat': '+4',
        'bull': '-3',
        'tiger': '+3',
        'rabbit': '+3',
        'dragon': '+1',
        'snake': '-3',
        'horse': '+4',
        'goat': '-4',
        'monkey': 'Лад',
        'rooster': '+5',
        'dog': '-3',
        'boar': '+3'
    },
    'rooster': {
        'rat': '+5',
        'bull': '-1',
        'tiger': '-3',
        'rabbit': '-7',
        'dragon': '-3',
        'snake': '-2',
        'horse': '-3',
        'goat': '+3',
        'monkey': '-5',
        'rooster': 'Лад',
        'dog': '+7',
        'boar': '-4'
    },
    'dog': {
        'rat': '-3',
        'bull': '+7',
        'tiger': '-1',
        'rabbit': '+2',
        'dragon': '-5',
        'snake': '-3',
        'horse': '+1',
        'goat': '+3',
        'monkey': '+3',
        'rooster': '-7',
        'dog': 'Лад',
        'boar': '+3'
    },
    'boar': {
        'rat': '-4',
        'bull': '+3',
        'tiger': '+5',
        'rabbit': '+1',
        'dragon': '+5',
        'snake': '-3',
        'horse': '-5',
        'goat': '-1',
        'monkey': '-3',
        'rooster': '+4',
        'dog': '-3',
        'boar': 'Лад'
    }
}

const compareAnimal = (animal1, animal2) => {
    return compatibility[animal1][animal2]
}
module.exports = compareAnimal